title: Junian.dev
description: Software Engineer
show_downloads: false
google_analytics: G-MKQK789F6L
theme: just-the-docs

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

github:
  is_project_page: false
  
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-commonmark-ghpages
  - just-the-docs

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-commonmark-ghpages
  - just-the-docs
